# -*- coding: utf-8 -*-
"""
Falta eliminar los botones del medio y agregar el quien hace la caja y quien fue el cajero
"""


import tkinter
def day():
    Day_window = tkinter.Tk()
    Day_window.geometry("1000x1500")
    Day_window.title("Planilla Diaria")
    Label_fill1 = tkinter.Label(Day_window, text = "                 ")
    Label_fill1.grid(row = 0, column = 8, columnspan = 3)
    Label_fill2 = tkinter.Label(Day_window, text = "                 ")
    Label_fill2.grid(row = 0, column = 9, columnspan = 3)
    Label_fill3 = tkinter.Label(Day_window, text = "                 ")
    Label_fill3.grid(row = 8, column = 0, columnspan = 3)
    Label_fill4 = tkinter.Label(Day_window, text = "                 ")
    Label_fill4.grid(row = 17, column = 0, columnspan = 3)
    Day_window.columnconfigure(0, weight=2)
    Day_window.columnconfigure(1, weight=1)
    Day_window.columnconfigure(2, weight=2)
    Day_window.columnconfigure(3, weight=2)
    Day_window.columnconfigure(4, weight=2)
    Day_window.columnconfigure(5, weight=2)
    Day_window.columnconfigure(6, weight=2)
    
    
    options1 = tkinter.StringVar(Day_window)
    options2 = tkinter.StringVar(Day_window)
    options3 = tkinter.StringVar(Day_window)
    options4 = tkinter.StringVar(Day_window)
    options5 = tkinter.StringVar(Day_window)
    options6 = tkinter.StringVar(Day_window)
    options1.set(" ")
    options2.set(" ")
    options3.set(" ")
    options4.set(" ")
    options5.set(" ")
    options6.set(" ")
    options_list = [" ", "Option 1", "Option 2", "Option 3", "Option 4"]
    Label_Title1 = tkinter.Label(Day_window, text = "                 Cuentas Corrientes")
    Label_Title1.grid(row = 0, column = 0, columnspan = 3)
    Label_Name = tkinter.Label(Day_window, text = "Nombre de la cuenta")
    Label_Name.grid(row = 1, column = 0)
    Label_Amount= tkinter.Label(Day_window, text = "Monto")
    Label_Amount.grid(row = 1, column = 1)
    name_list =tkinter.OptionMenu(Day_window, options1, *options_list)
    name_list.grid(row=2,column=0)
    name_list =tkinter.OptionMenu(Day_window, options2, *options_list)
    name_list.grid(row=3,column=0)
    name_list =tkinter.OptionMenu(Day_window, options3, *options_list)
    name_list.grid(row=4,column=0)
    name_list =tkinter.OptionMenu(Day_window, options4, *options_list)
    name_list.grid(row=5,column=0)
    name_list =tkinter.OptionMenu(Day_window, options5, *options_list)
    name_list.grid(row=6,column=0)
    name_list =tkinter.OptionMenu(Day_window, options6, *options_list)
    name_list.grid(row=7,column=0)
    Box_text1 = tkinter.Entry(Day_window)
    Box_text1.grid(row = 2, column = 1)
    Box_text2 = tkinter.Entry(Day_window)
    Box_text2.grid(row = 3, column = 1)
    Box_text3 = tkinter.Entry(Day_window)
    Box_text3.grid(row = 4, column = 1)
    Box_text4 = tkinter.Entry(Day_window)
    Box_text4.grid(row = 5, column = 1)
    Box_text5 = tkinter.Entry(Day_window)
    Box_text5.grid(row = 6, column = 1)
    Box_text6 = tkinter.Entry(Day_window)
    Box_text6.grid(row = 7, column = 1)
    
    
    poptions1 = tkinter.StringVar(Day_window)
    poptions2 = tkinter.StringVar(Day_window)
    poptions3 = tkinter.StringVar(Day_window)
    poptions4 = tkinter.StringVar(Day_window)
    poptions5 = tkinter.StringVar(Day_window)
    poptions6 = tkinter.StringVar(Day_window)
    poptions1.set(" ")
    poptions2.set(" ")
    poptions3.set(" ")
    poptions4.set(" ")
    poptions5.set(" ")
    poptions6.set(" ")
    Label_Title2 = tkinter.Label(Day_window, text = "            Pago de Cuentas Corrientes")
    Label_Title2.grid(row = 9, column = 0, columnspan = 3)
    Label_Name = tkinter.Label(Day_window, text = "Nombre de la cuenta")
    Label_Name.grid(row = 10, column = 0)
    Label_Amount= tkinter.Label(Day_window, text = "Monto")
    Label_Amount.grid(row = 10, column = 1)
    name_list =tkinter.OptionMenu(Day_window, poptions1, *options_list)
    name_list.grid(row=11,column=0)
    name_list =tkinter.OptionMenu(Day_window, poptions2, *options_list)
    name_list.grid(row=12,column=0)
    name_list =tkinter.OptionMenu(Day_window, poptions3, *options_list)
    name_list.grid(row=13,column=0)
    name_list =tkinter.OptionMenu(Day_window, poptions4, *options_list)
    name_list.grid(row=14,column=0)
    name_list =tkinter.OptionMenu(Day_window, poptions5, *options_list)
    name_list.grid(row=15,column=0)
    name_list =tkinter.OptionMenu(Day_window, poptions6, *options_list)
    name_list.grid(row=16,column=0)
    Box_textp1 = tkinter.Entry(Day_window)
    Box_textp1.grid(row = 11, column = 1)
    Box_textp2 = tkinter.Entry(Day_window)
    Box_textp2.grid(row = 12, column = 1)
    Box_textp3 = tkinter.Entry(Day_window)
    Box_textp3.grid(row = 13, column = 1)
    Box_textp4 = tkinter.Entry(Day_window)
    Box_textp4.grid(row = 14, column = 1)
    Box_textp5 = tkinter.Entry(Day_window)
    Box_textp5.grid(row = 15, column = 1)
    Box_textp6 = tkinter.Entry(Day_window)
    Box_textp6.grid(row = 16, column = 1)
    
    
    goptions1 = tkinter.StringVar(Day_window)
    goptions2 = tkinter.StringVar(Day_window)
    goptions3 = tkinter.StringVar(Day_window)
    goptions4 = tkinter.StringVar(Day_window)
    goptions5 = tkinter.StringVar(Day_window)
    goptions6 = tkinter.StringVar(Day_window)
    goptions1.set(" ")
    goptions2.set(" ")
    goptions3.set(" ")
    goptions4.set(" ")
    goptions5.set(" ")
    goptions6.set(" ")
    goptions_list = [" ", "Option 1", "Option 2", "Option 3", "Option 4"]
    Label_Title1 = tkinter.Label(Day_window, text = "                 Pagos de mercaderia")
    Label_Title1.grid(row = 0, column = 4, columnspan = 3)
    Label_NameG = tkinter.Label(Day_window, text = "Categoria")
    Label_NameG.grid(row = 1, column = 4)
    Label_Amount= tkinter.Label(Day_window, text = "Monto")
    Label_Amount.grid(row = 1, column = 5)
    name_list =tkinter.OptionMenu(Day_window, goptions1, *goptions_list)
    name_list.grid(row=2,column=4)
    name_list =tkinter.OptionMenu(Day_window, goptions2, *goptions_list)
    name_list.grid(row=3,column=4)
    name_list =tkinter.OptionMenu(Day_window, goptions3, *goptions_list)
    name_list.grid(row=4,column=4)
    name_list =tkinter.OptionMenu(Day_window, goptions4, *goptions_list)
    name_list.grid(row=5,column=4)
    name_list =tkinter.OptionMenu(Day_window, goptions5, *goptions_list)
    name_list.grid(row=6,column=4)
    name_list =tkinter.OptionMenu(Day_window, goptions6, *goptions_list)
    name_list.grid(row=7,column=4)
    Box_textg1 = tkinter.Entry(Day_window)
    Box_textg1.grid(row = 2, column = 5)
    Box_textg2 = tkinter.Entry(Day_window)
    Box_textg2.grid(row = 3, column = 5)
    Box_textg3 = tkinter.Entry(Day_window)
    Box_textg3.grid(row = 4, column = 5)
    Box_textg4 = tkinter.Entry(Day_window)
    Box_textg4.grid(row = 5, column = 5)
    Box_textg5 = tkinter.Entry(Day_window)
    Box_textg5.grid(row = 6, column = 5)
    Box_textg6 = tkinter.Entry(Day_window)
    Box_textg6.grid(row = 7, column = 5)
    
    
    eoptions1 = tkinter.StringVar(Day_window)
    eoptions2 = tkinter.StringVar(Day_window)
    eoptions3 = tkinter.StringVar(Day_window)
    eoptions4 = tkinter.StringVar(Day_window)
    eoptions5 = tkinter.StringVar(Day_window)
    eoptions6 = tkinter.StringVar(Day_window)
    eoptions7 = tkinter.StringVar(Day_window)
    eoptions8 = tkinter.StringVar(Day_window)
    eoptions9 = tkinter.StringVar(Day_window)
    eoptions1.set(" ")
    eoptions2.set(" ")
    eoptions3.set(" ")
    eoptions4.set(" ")
    eoptions5.set(" ")
    eoptions6.set(" ")
    eoptions7.set(" ")
    eoptions8.set(" ")
    eoptions9.set(" ")
    eoptions_list = [" ", "Option 1", "Option 2", "Option 3", "Option 4"]
    Label_Title1 = tkinter.Label(Day_window, text = "                 Retiros empleados")
    Label_Title1.grid(row = 9, column = 4, columnspan = 3)
    Label_NameG = tkinter.Label(Day_window, text = "Nombre del empleado")
    Label_NameG.grid(row = 10, column = 4)
    Label_Amount= tkinter.Label(Day_window, text = "Monto")
    Label_Amount.grid(row = 10, column = 5)
    name_list =tkinter.OptionMenu(Day_window, eoptions1, *eoptions_list)
    name_list.grid(row=11,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions2, *eoptions_list)
    name_list.grid(row=12,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions3, *eoptions_list)
    name_list.grid(row=13,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions4, *eoptions_list)
    name_list.grid(row=14,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions5, *eoptions_list)
    name_list.grid(row=15,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions6, *eoptions_list)
    name_list.grid(row=16,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions7, *eoptions_list)
    name_list.grid(row=17,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions8, *eoptions_list)
    name_list.grid(row=18,column=4)
    name_list =tkinter.OptionMenu(Day_window, eoptions9, *eoptions_list)
    name_list.grid(row=19,column=4)
    Box_texte1 = tkinter.Entry(Day_window)
    Box_texte1.grid(row = 11, column = 5)
    Box_texte2 = tkinter.Entry(Day_window)
    Box_texte2.grid(row = 12, column = 5)
    Box_texte3 = tkinter.Entry(Day_window)
    Box_texte3.grid(row = 13, column = 5)
    Box_texte4 = tkinter.Entry(Day_window)
    Box_texte4.grid(row = 14, column = 5)
    Box_texte5 = tkinter.Entry(Day_window)
    Box_texte5.grid(row = 15, column = 5)
    Box_texte6 = tkinter.Entry(Day_window)
    Box_texte6.grid(row = 16, column = 5)
    Box_texte6 = tkinter.Entry(Day_window)
    Box_texte6.grid(row = 17, column = 5)
    Box_texte6 = tkinter.Entry(Day_window)
    Box_texte6.grid(row = 18, column = 5)
    Box_texte6 = tkinter.Entry(Day_window)
    Box_texte6.grid(row = 19, column = 5)
    
    
    
    Label_Title2 = tkinter.Label(Day_window, text = "            Debitos")
    Label_Title2.grid(row = 18, column = 0, columnspan = 3)
    Box_textd1 = tkinter.Entry(Day_window)
    Box_textd1.grid(row = 19, column = 1)
    Box_textd2 = tkinter.Entry(Day_window)
    Box_textd2.grid(row = 20, column = 1)
    Box_textd3 = tkinter.Entry(Day_window)
    Box_textd3.grid(row = 21, column = 1)
    Box_textd4 = tkinter.Entry(Day_window)
    Box_textd4.grid(row = 22, column = 1)
    
    
    Label_Title2 = tkinter.Label(Day_window, text = "   Efectivo")
    Label_Title2.grid(row = 18, column = 2, columnspan = 3)
    Box_textc1 = tkinter.Entry(Day_window)
    Box_textc1.grid(row = 19, column = 3)
    
    

    
    def Text_from_box():
        Text = options1.get()
        print(Text)
    Expense_Button = tkinter.Button(Day_window, text = "Cargar", command = Text_from_box)
    Expense_Button.grid(row = 10, column = 3)
    def Update():
        Entry = False
    Finish_Button = tkinter.Button(Day_window, text= "Finalizar", command = Update)
    Finish_Button.grid(row =10, column = 2)
    Day_window.mainloop()