# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Plantilla.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1183, 868)
        Dialog.setSizeGripEnabled(True)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1181, 861))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.calendarWidget = QtWidgets.QCalendarWidget(self.tab_3)
        self.calendarWidget.setGeometry(QtCore.QRect(10, 210, 451, 251))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.calendarWidget.setFont(font)
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Argentina))
        self.calendarWidget.setObjectName("calendarWidget")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(300, 10, 661, 111))
        font = QtGui.QFont()
        font.setPointSize(34)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.tab_3)
        self.label_18.setGeometry(QtCore.QRect(590, 130, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_3)
        self.label_19.setGeometry(QtCore.QRect(510, 210, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_3)
        self.label_20.setGeometry(QtCore.QRect(510, 290, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.txtFrancoManana = QtWidgets.QLineEdit(self.tab_3)
        self.txtFrancoManana.setEnabled(False)
        self.txtFrancoManana.setGeometry(QtCore.QRect(670, 220, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtFrancoManana.setFont(font)
        self.txtFrancoManana.setObjectName("txtFrancoManana")
        self.txtFrancoTarde = QtWidgets.QLineEdit(self.tab_3)
        self.txtFrancoTarde.setEnabled(False)
        self.txtFrancoTarde.setGeometry(QtCore.QRect(670, 300, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtFrancoTarde.setFont(font)
        self.txtFrancoTarde.setObjectName("txtFrancoTarde")
        self.label_21 = QtWidgets.QLabel(self.tab_3)
        self.label_21.setGeometry(QtCore.QRect(510, 380, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.txtCarpeta = QtWidgets.QLineEdit(self.tab_3)
        self.txtCarpeta.setEnabled(False)
        self.txtCarpeta.setGeometry(QtCore.QRect(670, 390, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtCarpeta.setFont(font)
        self.txtCarpeta.setObjectName("txtCarpeta")
        self.label_22 = QtWidgets.QLabel(self.tab_3)
        self.label_22.setGeometry(QtCore.QRect(30, 500, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayoutWidget_10 = QtWidgets.QWidget(self.tab_3)
        self.verticalLayoutWidget_10.setGeometry(QtCore.QRect(20, 550, 1111, 281))
        self.verticalLayoutWidget_10.setObjectName("verticalLayoutWidget_10")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_10)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.txtTarea1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.txtTarea1.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtTarea1.setFont(font)
        self.txtTarea1.setObjectName("txtTarea1")
        self.verticalLayout_14.addWidget(self.txtTarea1)
        self.txtTarea2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.txtTarea2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtTarea2.setFont(font)
        self.txtTarea2.setObjectName("txtTarea2")
        self.verticalLayout_14.addWidget(self.txtTarea2)
        self.txtTarea3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.txtTarea3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtTarea3.setFont(font)
        self.txtTarea3.setObjectName("txtTarea3")
        self.verticalLayout_14.addWidget(self.txtTarea3)
        self.txtTarea4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.txtTarea4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtTarea4.setFont(font)
        self.txtTarea4.setText("")
        self.txtTarea4.setObjectName("txtTarea4")
        self.verticalLayout_14.addWidget(self.txtTarea4)
        self.txtTarea5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.txtTarea5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtTarea5.setFont(font)
        self.txtTarea5.setObjectName("txtTarea5")
        self.verticalLayout_14.addWidget(self.txtTarea5)
        self.txtTarea6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_10)
        self.txtTarea6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.txtTarea6.setFont(font)
        self.txtTarea6.setObjectName("txtTarea6")
        self.verticalLayout_14.addWidget(self.txtTarea6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(280, 480, 111, 281))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.txtCobros1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCobros1.sizePolicy().hasHeightForWidth())
        self.txtCobros1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCobros1.setFont(font)
        self.txtCobros1.setText("")
        self.txtCobros1.setObjectName("txtCobros1")
        self.verticalLayout_6.addWidget(self.txtCobros1)
        self.txtCobros2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCobros2.sizePolicy().hasHeightForWidth())
        self.txtCobros2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCobros2.setFont(font)
        self.txtCobros2.setText("")
        self.txtCobros2.setObjectName("txtCobros2")
        self.verticalLayout_6.addWidget(self.txtCobros2)
        self.txtCobros3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCobros3.sizePolicy().hasHeightForWidth())
        self.txtCobros3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCobros3.setFont(font)
        self.txtCobros3.setText("")
        self.txtCobros3.setObjectName("txtCobros3")
        self.verticalLayout_6.addWidget(self.txtCobros3)
        self.txtCobros4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCobros4.sizePolicy().hasHeightForWidth())
        self.txtCobros4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCobros4.setFont(font)
        self.txtCobros4.setText("")
        self.txtCobros4.setObjectName("txtCobros4")
        self.verticalLayout_6.addWidget(self.txtCobros4)
        self.txtCobros5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCobros5.sizePolicy().hasHeightForWidth())
        self.txtCobros5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCobros5.setFont(font)
        self.txtCobros5.setText("")
        self.txtCobros5.setObjectName("txtCobros5")
        self.verticalLayout_6.addWidget(self.txtCobros5)
        self.txtCobros6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCobros6.sizePolicy().hasHeightForWidth())
        self.txtCobros6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCobros6.setFont(font)
        self.txtCobros6.setText("")
        self.txtCobros6.setObjectName("txtCobros6")
        self.verticalLayout_6.addWidget(self.txtCobros6)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(280, 110, 111, 281))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.txtCuentas1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCuentas1.sizePolicy().hasHeightForWidth())
        self.txtCuentas1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCuentas1.setFont(font)
        self.txtCuentas1.setText("")
        self.txtCuentas1.setObjectName("txtCuentas1")
        self.verticalLayout_3.addWidget(self.txtCuentas1)
        self.txtCuentas2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCuentas2.sizePolicy().hasHeightForWidth())
        self.txtCuentas2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCuentas2.setFont(font)
        self.txtCuentas2.setText("")
        self.txtCuentas2.setObjectName("txtCuentas2")
        self.verticalLayout_3.addWidget(self.txtCuentas2)
        self.txtCuentas3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCuentas3.sizePolicy().hasHeightForWidth())
        self.txtCuentas3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCuentas3.setFont(font)
        self.txtCuentas3.setText("")
        self.txtCuentas3.setObjectName("txtCuentas3")
        self.verticalLayout_3.addWidget(self.txtCuentas3)
        self.txtCuentas4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCuentas4.sizePolicy().hasHeightForWidth())
        self.txtCuentas4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCuentas4.setFont(font)
        self.txtCuentas4.setText("")
        self.txtCuentas4.setObjectName("txtCuentas4")
        self.verticalLayout_3.addWidget(self.txtCuentas4)
        self.txtCuentas5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCuentas5.sizePolicy().hasHeightForWidth())
        self.txtCuentas5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCuentas5.setFont(font)
        self.txtCuentas5.setText("")
        self.txtCuentas5.setObjectName("txtCuentas5")
        self.verticalLayout_3.addWidget(self.txtCuentas5)
        self.txtCuentas6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtCuentas6.sizePolicy().hasHeightForWidth())
        self.txtCuentas6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtCuentas6.setFont(font)
        self.txtCuentas6.setText("")
        self.txtCuentas6.setObjectName("txtCuentas6")
        self.verticalLayout_3.addWidget(self.txtCuentas6)
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(20, 400, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 110, 241, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.cmbCuentas1 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCuentas1.sizePolicy().hasHeightForWidth())
        self.cmbCuentas1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCuentas1.setFont(font)
        self.cmbCuentas1.setObjectName("cmbCuentas1")
        self.verticalLayout.addWidget(self.cmbCuentas1)
        self.cmbCuentas2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCuentas2.sizePolicy().hasHeightForWidth())
        self.cmbCuentas2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCuentas2.setFont(font)
        self.cmbCuentas2.setObjectName("cmbCuentas2")
        self.verticalLayout.addWidget(self.cmbCuentas2)
        self.cmbCuentas3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCuentas3.sizePolicy().hasHeightForWidth())
        self.cmbCuentas3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCuentas3.setFont(font)
        self.cmbCuentas3.setObjectName("cmbCuentas3")
        self.verticalLayout.addWidget(self.cmbCuentas3)
        self.cmbCuentas4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCuentas4.sizePolicy().hasHeightForWidth())
        self.cmbCuentas4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCuentas4.setFont(font)
        self.cmbCuentas4.setObjectName("cmbCuentas4")
        self.verticalLayout.addWidget(self.cmbCuentas4)
        self.cmbCuentas5 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCuentas5.sizePolicy().hasHeightForWidth())
        self.cmbCuentas5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCuentas5.setFont(font)
        self.cmbCuentas5.setObjectName("cmbCuentas5")
        self.verticalLayout.addWidget(self.cmbCuentas5)
        self.cmbCuentas6 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCuentas6.sizePolicy().hasHeightForWidth())
        self.cmbCuentas6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCuentas6.setFont(font)
        self.cmbCuentas6.setObjectName("cmbCuentas6")
        self.verticalLayout.addWidget(self.cmbCuentas6)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(450, 110, 241, 281))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmbEmpleado1 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEmpleado1.sizePolicy().hasHeightForWidth())
        self.cmbEmpleado1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbEmpleado1.setFont(font)
        self.cmbEmpleado1.setObjectName("cmbEmpleado1")
        self.verticalLayout_2.addWidget(self.cmbEmpleado1)
        self.cmbEmpleado2 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEmpleado2.sizePolicy().hasHeightForWidth())
        self.cmbEmpleado2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbEmpleado2.setFont(font)
        self.cmbEmpleado2.setObjectName("cmbEmpleado2")
        self.verticalLayout_2.addWidget(self.cmbEmpleado2)
        self.cmbEmpleado3 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEmpleado3.sizePolicy().hasHeightForWidth())
        self.cmbEmpleado3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbEmpleado3.setFont(font)
        self.cmbEmpleado3.setObjectName("cmbEmpleado3")
        self.verticalLayout_2.addWidget(self.cmbEmpleado3)
        self.cmbEmpleado4 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEmpleado4.sizePolicy().hasHeightForWidth())
        self.cmbEmpleado4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbEmpleado4.setFont(font)
        self.cmbEmpleado4.setObjectName("cmbEmpleado4")
        self.verticalLayout_2.addWidget(self.cmbEmpleado4)
        self.cmbEmpleado5 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEmpleado5.sizePolicy().hasHeightForWidth())
        self.cmbEmpleado5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbEmpleado5.setFont(font)
        self.cmbEmpleado5.setObjectName("cmbEmpleado5")
        self.verticalLayout_2.addWidget(self.cmbEmpleado5)
        self.cmbEmpleado6 = QtWidgets.QComboBox(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbEmpleado6.sizePolicy().hasHeightForWidth())
        self.cmbEmpleado6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbEmpleado6.setFont(font)
        self.cmbEmpleado6.setObjectName("cmbEmpleado6")
        self.verticalLayout_2.addWidget(self.cmbEmpleado6)
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(460, 400, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 30, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_10 = QtWidgets.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(460, 430, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.btnFinalizar = QtWidgets.QPushButton(self.tab)
        self.btnFinalizar.setGeometry(QtCore.QRect(900, 630, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnFinalizar.setFont(font)
        self.btnFinalizar.setObjectName("btnFinalizar")
        self.label_11 = QtWidgets.QLabel(self.tab)
        self.label_11.setGeometry(QtCore.QRect(730, 430, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(460, 30, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayoutWidget_8 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_8.setGeometry(QtCore.QRect(720, 480, 111, 281))
        self.verticalLayoutWidget_8.setObjectName("verticalLayoutWidget_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_8)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.txtGastos1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGastos1.sizePolicy().hasHeightForWidth())
        self.txtGastos1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtGastos1.setFont(font)
        self.txtGastos1.setText("")
        self.txtGastos1.setObjectName("txtGastos1")
        self.verticalLayout_12.addWidget(self.txtGastos1)
        self.txtGastos2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGastos2.sizePolicy().hasHeightForWidth())
        self.txtGastos2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtGastos2.setFont(font)
        self.txtGastos2.setText("")
        self.txtGastos2.setObjectName("txtGastos2")
        self.verticalLayout_12.addWidget(self.txtGastos2)
        self.txtGastos3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGastos3.sizePolicy().hasHeightForWidth())
        self.txtGastos3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtGastos3.setFont(font)
        self.txtGastos3.setText("")
        self.txtGastos3.setObjectName("txtGastos3")
        self.verticalLayout_12.addWidget(self.txtGastos3)
        self.txtGastos4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGastos4.sizePolicy().hasHeightForWidth())
        self.txtGastos4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtGastos4.setFont(font)
        self.txtGastos4.setText("")
        self.txtGastos4.setObjectName("txtGastos4")
        self.verticalLayout_12.addWidget(self.txtGastos4)
        self.txtGastos5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGastos5.sizePolicy().hasHeightForWidth())
        self.txtGastos5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtGastos5.setFont(font)
        self.txtGastos5.setText("")
        self.txtGastos5.setObjectName("txtGastos5")
        self.verticalLayout_12.addWidget(self.txtGastos5)
        self.txtGastos6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGastos6.sizePolicy().hasHeightForWidth())
        self.txtGastos6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtGastos6.setFont(font)
        self.txtGastos6.setText("")
        self.txtGastos6.setObjectName("txtGastos6")
        self.verticalLayout_12.addWidget(self.txtGastos6)
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(290, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_16 = QtWidgets.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(880, 490, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 480, 241, 281))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.cmbCobros1 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCobros1.sizePolicy().hasHeightForWidth())
        self.cmbCobros1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCobros1.setFont(font)
        self.cmbCobros1.setObjectName("cmbCobros1")
        self.verticalLayout_5.addWidget(self.cmbCobros1)
        self.cmbCobros2 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCobros2.sizePolicy().hasHeightForWidth())
        self.cmbCobros2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCobros2.setFont(font)
        self.cmbCobros2.setObjectName("cmbCobros2")
        self.verticalLayout_5.addWidget(self.cmbCobros2)
        self.cmbCobros3 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCobros3.sizePolicy().hasHeightForWidth())
        self.cmbCobros3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCobros3.setFont(font)
        self.cmbCobros3.setObjectName("cmbCobros3")
        self.verticalLayout_5.addWidget(self.cmbCobros3)
        self.cmbCobros4 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCobros4.sizePolicy().hasHeightForWidth())
        self.cmbCobros4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCobros4.setFont(font)
        self.cmbCobros4.setObjectName("cmbCobros4")
        self.verticalLayout_5.addWidget(self.cmbCobros4)
        self.cmbCobros5 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCobros5.sizePolicy().hasHeightForWidth())
        self.cmbCobros5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCobros5.setFont(font)
        self.cmbCobros5.setObjectName("cmbCobros5")
        self.verticalLayout_5.addWidget(self.cmbCobros5)
        self.cmbCobros6 = QtWidgets.QComboBox(self.verticalLayoutWidget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCobros6.sizePolicy().hasHeightForWidth())
        self.cmbCobros6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCobros6.setFont(font)
        self.cmbCobros6.setObjectName("cmbCobros6")
        self.verticalLayout_5.addWidget(self.cmbCobros6)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(880, 420, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(950, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.cmbCajero = QtWidgets.QComboBox(self.tab)
        self.cmbCajero.setGeometry(QtCore.QRect(1010, 340, 151, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbCajero.sizePolicy().hasHeightForWidth())
        self.cmbCajero.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbCajero.setFont(font)
        self.cmbCajero.setObjectName("cmbCajero")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(450, 480, 241, 281))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.cmbGastos1 = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGastos1.sizePolicy().hasHeightForWidth())
        self.cmbGastos1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbGastos1.setFont(font)
        self.cmbGastos1.setObjectName("cmbGastos1")
        self.verticalLayout_11.addWidget(self.cmbGastos1)
        self.cmbGastos2 = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGastos2.sizePolicy().hasHeightForWidth())
        self.cmbGastos2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbGastos2.setFont(font)
        self.cmbGastos2.setObjectName("cmbGastos2")
        self.verticalLayout_11.addWidget(self.cmbGastos2)
        self.cmbGastos3 = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGastos3.sizePolicy().hasHeightForWidth())
        self.cmbGastos3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbGastos3.setFont(font)
        self.cmbGastos3.setObjectName("cmbGastos3")
        self.verticalLayout_11.addWidget(self.cmbGastos3)
        self.cmbGastos4 = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGastos4.sizePolicy().hasHeightForWidth())
        self.cmbGastos4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbGastos4.setFont(font)
        self.cmbGastos4.setObjectName("cmbGastos4")
        self.verticalLayout_11.addWidget(self.cmbGastos4)
        self.cmbGastos5 = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGastos5.sizePolicy().hasHeightForWidth())
        self.cmbGastos5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbGastos5.setFont(font)
        self.cmbGastos5.setObjectName("cmbGastos5")
        self.verticalLayout_11.addWidget(self.cmbGastos5)
        self.cmbGastos6 = QtWidgets.QComboBox(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbGastos6.sizePolicy().hasHeightForWidth())
        self.cmbGastos6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cmbGastos6.setFont(font)
        self.cmbGastos6.setObjectName("cmbGastos6")
        self.verticalLayout_11.addWidget(self.cmbGastos6)
        self.label_14 = QtWidgets.QLabel(self.tab)
        self.label_14.setGeometry(QtCore.QRect(880, 340, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(290, 430, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(460, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(20, 430, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayoutWidget_9 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_9.setGeometry(QtCore.QRect(920, 110, 171, 121))
        self.verticalLayoutWidget_9.setObjectName("verticalLayoutWidget_9")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_9)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.txtDebito1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDebito1.sizePolicy().hasHeightForWidth())
        self.txtDebito1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDebito1.setFont(font)
        self.txtDebito1.setText("")
        self.txtDebito1.setObjectName("txtDebito1")
        self.verticalLayout_13.addWidget(self.txtDebito1)
        self.txtDebito2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDebito2.sizePolicy().hasHeightForWidth())
        self.txtDebito2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDebito2.setFont(font)
        self.txtDebito2.setText("")
        self.txtDebito2.setObjectName("txtDebito2")
        self.verticalLayout_13.addWidget(self.txtDebito2)
        self.txtDebito3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDebito3.sizePolicy().hasHeightForWidth())
        self.txtDebito3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDebito3.setFont(font)
        self.txtDebito3.setText("")
        self.txtDebito3.setObjectName("txtDebito3")
        self.verticalLayout_13.addWidget(self.txtDebito3)
        self.txtTotal = QtWidgets.QLineEdit(self.tab)
        self.txtTotal.setEnabled(False)
        self.txtTotal.setGeometry(QtCore.QRect(990, 490, 169, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTotal.sizePolicy().hasHeightForWidth())
        self.txtTotal.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtTotal.setFont(font)
        self.txtTotal.setText("")
        self.txtTotal.setObjectName("txtTotal")
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(720, 110, 111, 281))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.txtEmpleado1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmpleado1.sizePolicy().hasHeightForWidth())
        self.txtEmpleado1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEmpleado1.setFont(font)
        self.txtEmpleado1.setText("")
        self.txtEmpleado1.setObjectName("txtEmpleado1")
        self.verticalLayout_4.addWidget(self.txtEmpleado1)
        self.txtEmpleado2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmpleado2.sizePolicy().hasHeightForWidth())
        self.txtEmpleado2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEmpleado2.setFont(font)
        self.txtEmpleado2.setText("")
        self.txtEmpleado2.setObjectName("txtEmpleado2")
        self.verticalLayout_4.addWidget(self.txtEmpleado2)
        self.txtEmpleado3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmpleado3.sizePolicy().hasHeightForWidth())
        self.txtEmpleado3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEmpleado3.setFont(font)
        self.txtEmpleado3.setText("")
        self.txtEmpleado3.setObjectName("txtEmpleado3")
        self.verticalLayout_4.addWidget(self.txtEmpleado3)
        self.txtEmpleado4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmpleado4.sizePolicy().hasHeightForWidth())
        self.txtEmpleado4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEmpleado4.setFont(font)
        self.txtEmpleado4.setText("")
        self.txtEmpleado4.setObjectName("txtEmpleado4")
        self.verticalLayout_4.addWidget(self.txtEmpleado4)
        self.txtEmpleado5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmpleado5.sizePolicy().hasHeightForWidth())
        self.txtEmpleado5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEmpleado5.setFont(font)
        self.txtEmpleado5.setText("")
        self.txtEmpleado5.setObjectName("txtEmpleado5")
        self.verticalLayout_4.addWidget(self.txtEmpleado5)
        self.txtEmpleado6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEmpleado6.sizePolicy().hasHeightForWidth())
        self.txtEmpleado6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEmpleado6.setFont(font)
        self.txtEmpleado6.setText("")
        self.txtEmpleado6.setObjectName("txtEmpleado6")
        self.verticalLayout_4.addWidget(self.txtEmpleado6)
        self.txtEfectivo = QtWidgets.QLineEdit(self.tab)
        self.txtEfectivo.setGeometry(QtCore.QRect(990, 420, 169, 36))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtEfectivo.sizePolicy().hasHeightForWidth())
        self.txtEfectivo.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtEfectivo.setFont(font)
        self.txtEfectivo.setText("")
        self.txtEfectivo.setObjectName("txtEfectivo")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(730, 60, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.cmbDatos1 = QtWidgets.QComboBox(self.tab_2)
        self.cmbDatos1.setGeometry(QtCore.QRect(230, 30, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDatos1.setFont(font)
        self.cmbDatos1.setObjectName("cmbDatos1")
        self.label_23 = QtWidgets.QLabel(self.tab_2)
        self.label_23.setGeometry(QtCore.QRect(70, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(490, 20, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.txtDatos = QtWidgets.QLineEdit(self.tab_2)
        self.txtDatos.setGeometry(QtCore.QRect(650, 20, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDatos.setFont(font)
        self.txtDatos.setObjectName("txtDatos")
        self.txtDatos2 = QtWidgets.QLineEdit(self.tab_2)
        self.txtDatos2.setGeometry(QtCore.QRect(650, 120, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDatos2.setFont(font)
        self.txtDatos2.setObjectName("txtDatos2")
        self.label_25 = QtWidgets.QLabel(self.tab_2)
        self.label_25.setGeometry(QtCore.QRect(70, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.cmbDatos2 = QtWidgets.QComboBox(self.tab_2)
        self.cmbDatos2.setGeometry(QtCore.QRect(230, 130, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDatos2.setFont(font)
        self.cmbDatos2.setObjectName("cmbDatos2")
        self.label_26 = QtWidgets.QLabel(self.tab_2)
        self.label_26.setGeometry(QtCore.QRect(490, 120, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.txtDatos3 = QtWidgets.QLineEdit(self.tab_2)
        self.txtDatos3.setGeometry(QtCore.QRect(650, 220, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDatos3.setFont(font)
        self.txtDatos3.setObjectName("txtDatos3")
        self.label_27 = QtWidgets.QLabel(self.tab_2)
        self.label_27.setGeometry(QtCore.QRect(490, 320, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_2)
        self.label_28.setGeometry(QtCore.QRect(70, 220, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.cmbDatos4 = QtWidgets.QComboBox(self.tab_2)
        self.cmbDatos4.setGeometry(QtCore.QRect(230, 330, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDatos4.setFont(font)
        self.cmbDatos4.setObjectName("cmbDatos4")
        self.txtDatos4 = QtWidgets.QLineEdit(self.tab_2)
        self.txtDatos4.setGeometry(QtCore.QRect(650, 320, 251, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtDatos4.setFont(font)
        self.txtDatos4.setObjectName("txtDatos4")
        self.cmbDatos3 = QtWidgets.QComboBox(self.tab_2)
        self.cmbDatos3.setGeometry(QtCore.QRect(230, 230, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDatos3.setFont(font)
        self.cmbDatos3.setObjectName("cmbDatos3")
        self.label_29 = QtWidgets.QLabel(self.tab_2)
        self.label_29.setGeometry(QtCore.QRect(490, 220, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.tab_2)
        self.label_30.setGeometry(QtCore.QRect(70, 320, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.btnCargar = QtWidgets.QPushButton(self.tab_2)
        self.btnCargar.setGeometry(QtCore.QRect(410, 510, 181, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnCargar.setFont(font)
        self.btnCargar.setObjectName("btnCargar")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 20, 951, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_31 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.horizontalLayout.addWidget(self.label_31)
        self.label_32 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout.addWidget(self.label_32)
        self.label_33 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.horizontalLayout.addWidget(self.label_33)
        self.verticalLayoutWidget_11 = QtWidgets.QWidget(self.tab_4)
        self.verticalLayoutWidget_11.setGeometry(QtCore.QRect(10, 100, 211, 521))
        self.verticalLayoutWidget_11.setObjectName("verticalLayoutWidget_11")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_11)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.txtFranco1 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco1.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco1.setFont(font)
        self.txtFranco1.setObjectName("txtFranco1")
        self.verticalLayout_15.addWidget(self.txtFranco1)
        self.txtFranco2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco2.setFont(font)
        self.txtFranco2.setObjectName("txtFranco2")
        self.verticalLayout_15.addWidget(self.txtFranco2)
        self.txtFranco3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco3.setFont(font)
        self.txtFranco3.setObjectName("txtFranco3")
        self.verticalLayout_15.addWidget(self.txtFranco3)
        self.txtFranco4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco4.setFont(font)
        self.txtFranco4.setObjectName("txtFranco4")
        self.verticalLayout_15.addWidget(self.txtFranco4)
        self.txtFranco5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco5.setFont(font)
        self.txtFranco5.setObjectName("txtFranco5")
        self.verticalLayout_15.addWidget(self.txtFranco5)
        self.txtFranco6 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco6.setFont(font)
        self.txtFranco6.setObjectName("txtFranco6")
        self.verticalLayout_15.addWidget(self.txtFranco6)
        self.txtFranco7 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco7.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco7.setFont(font)
        self.txtFranco7.setObjectName("txtFranco7")
        self.verticalLayout_15.addWidget(self.txtFranco7)
        self.txtFranco8 = QtWidgets.QLineEdit(self.verticalLayoutWidget_11)
        self.txtFranco8.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.txtFranco8.setFont(font)
        self.txtFranco8.setObjectName("txtFranco8")
        self.verticalLayout_15.addWidget(self.txtFranco8)
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(640, 100, 341, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.chkCarpeta7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta7.setFont(font)
        self.chkCarpeta7.setObjectName("chkCarpeta7")
        self.gridLayout.addWidget(self.chkCarpeta7, 6, 0, 1, 1)
        self.chkCarpeta4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta4.setFont(font)
        self.chkCarpeta4.setObjectName("chkCarpeta4")
        self.gridLayout.addWidget(self.chkCarpeta4, 3, 0, 1, 1)
        self.chkCarpeta6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta6.setFont(font)
        self.chkCarpeta6.setObjectName("chkCarpeta6")
        self.gridLayout.addWidget(self.chkCarpeta6, 5, 0, 1, 1)
        self.dateCarpeta1 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta1.setFont(font)
        self.dateCarpeta1.setObjectName("dateCarpeta1")
        self.gridLayout.addWidget(self.dateCarpeta1, 0, 1, 1, 1)
        self.chkCarpeta5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta5.setFont(font)
        self.chkCarpeta5.setObjectName("chkCarpeta5")
        self.gridLayout.addWidget(self.chkCarpeta5, 4, 0, 1, 1)
        self.chkCarpeta3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta3.setFont(font)
        self.chkCarpeta3.setObjectName("chkCarpeta3")
        self.gridLayout.addWidget(self.chkCarpeta3, 2, 0, 1, 1)
        self.chkCarpeta2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta2.setFont(font)
        self.chkCarpeta2.setObjectName("chkCarpeta2")
        self.gridLayout.addWidget(self.chkCarpeta2, 1, 0, 1, 1)
        self.chkCarpeta1 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta1.setFont(font)
        self.chkCarpeta1.setObjectName("chkCarpeta1")
        self.gridLayout.addWidget(self.chkCarpeta1, 0, 0, 1, 1)
        self.chkCarpeta8 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.chkCarpeta8.setFont(font)
        self.chkCarpeta8.setObjectName("chkCarpeta8")
        self.gridLayout.addWidget(self.chkCarpeta8, 7, 0, 1, 1)
        self.dateCarpeta2 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta2.setFont(font)
        self.dateCarpeta2.setObjectName("dateCarpeta2")
        self.gridLayout.addWidget(self.dateCarpeta2, 1, 1, 1, 1)
        self.dateCarpeta3 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta3.setFont(font)
        self.dateCarpeta3.setObjectName("dateCarpeta3")
        self.gridLayout.addWidget(self.dateCarpeta3, 2, 1, 1, 1)
        self.dateCarpeta4 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta4.setFont(font)
        self.dateCarpeta4.setObjectName("dateCarpeta4")
        self.gridLayout.addWidget(self.dateCarpeta4, 3, 1, 1, 1)
        self.dateCarpeta5 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta5.setFont(font)
        self.dateCarpeta5.setObjectName("dateCarpeta5")
        self.gridLayout.addWidget(self.dateCarpeta5, 4, 1, 1, 1)
        self.dateCarpeta6 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta6.setFont(font)
        self.dateCarpeta6.setObjectName("dateCarpeta6")
        self.gridLayout.addWidget(self.dateCarpeta6, 5, 1, 1, 1)
        self.dateCarpeta7 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta7.setFont(font)
        self.dateCarpeta7.setObjectName("dateCarpeta7")
        self.gridLayout.addWidget(self.dateCarpeta7, 6, 1, 1, 1)
        self.dateCarpeta8 = QtWidgets.QDateEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.dateCarpeta8.setFont(font)
        self.dateCarpeta8.setObjectName("dateCarpeta8")
        self.gridLayout.addWidget(self.dateCarpeta8, 7, 1, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_4)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(250, 100, 361, 521))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.cmbDiaFranco2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco2.setFont(font)
        self.cmbDiaFranco2.setObjectName("cmbDiaFranco2")
        self.gridLayout_2.addWidget(self.cmbDiaFranco2, 1, 0, 1, 1)
        self.cmbTurnoFranco2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco2.setFont(font)
        self.cmbTurnoFranco2.setObjectName("cmbTurnoFranco2")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco2, 1, 1, 1, 1)
        self.cmbTurnoFranco7 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco7.setFont(font)
        self.cmbTurnoFranco7.setObjectName("cmbTurnoFranco7")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco7, 6, 1, 1, 1)
        self.cmbTurnoFranco1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco1.setFont(font)
        self.cmbTurnoFranco1.setObjectName("cmbTurnoFranco1")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco1, 0, 1, 1, 1)
        self.cmbDiaFranco6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco6.setFont(font)
        self.cmbDiaFranco6.setObjectName("cmbDiaFranco6")
        self.gridLayout_2.addWidget(self.cmbDiaFranco6, 5, 0, 1, 1)
        self.cmbTurnoFranco3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco3.setFont(font)
        self.cmbTurnoFranco3.setObjectName("cmbTurnoFranco3")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco3, 2, 1, 1, 1)
        self.cmbDiaFranco3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco3.setFont(font)
        self.cmbDiaFranco3.setObjectName("cmbDiaFranco3")
        self.gridLayout_2.addWidget(self.cmbDiaFranco3, 2, 0, 1, 1)
        self.cmbTurnoFranco4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco4.setFont(font)
        self.cmbTurnoFranco4.setObjectName("cmbTurnoFranco4")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco4, 3, 1, 1, 1)
        self.cmbDiaFranco4 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco4.setFont(font)
        self.cmbDiaFranco4.setObjectName("cmbDiaFranco4")
        self.gridLayout_2.addWidget(self.cmbDiaFranco4, 3, 0, 1, 1)
        self.cmbTurnoFranco6 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco6.setFont(font)
        self.cmbTurnoFranco6.setObjectName("cmbTurnoFranco6")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco6, 5, 1, 1, 1)
        self.cmbDiaFranco7 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco7.setFont(font)
        self.cmbDiaFranco7.setObjectName("cmbDiaFranco7")
        self.gridLayout_2.addWidget(self.cmbDiaFranco7, 6, 0, 1, 1)
        self.cmbTurnoFranco5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco5.setFont(font)
        self.cmbTurnoFranco5.setObjectName("cmbTurnoFranco5")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco5, 4, 1, 1, 1)
        self.cmbDiaFranco5 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco5.setFont(font)
        self.cmbDiaFranco5.setObjectName("cmbDiaFranco5")
        self.gridLayout_2.addWidget(self.cmbDiaFranco5, 4, 0, 1, 1)
        self.cmbDiaFranco1 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco1.setFont(font)
        self.cmbDiaFranco1.setObjectName("cmbDiaFranco1")
        self.gridLayout_2.addWidget(self.cmbDiaFranco1, 0, 0, 1, 1)
        self.cmbDiaFranco8 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbDiaFranco8.setFont(font)
        self.cmbDiaFranco8.setObjectName("cmbDiaFranco8")
        self.gridLayout_2.addWidget(self.cmbDiaFranco8, 7, 0, 1, 1)
        self.cmbTurnoFranco8 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.cmbTurnoFranco8.setFont(font)
        self.cmbTurnoFranco8.setObjectName("cmbTurnoFranco8")
        self.gridLayout_2.addWidget(self.cmbTurnoFranco8, 7, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_17.setText(_translate("Dialog", "Autoservicio Miguel Angel"))
        self.label_18.setText(_translate("Dialog", "Francos"))
        self.label_19.setText(_translate("Dialog", "Mañana"))
        self.label_20.setText(_translate("Dialog", "Tarde"))
        self.label_21.setText(_translate("Dialog", "Carpeta"))
        self.label_22.setText(_translate("Dialog", "Cosas para hoy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Inicio"))
        self.label_2.setText(_translate("Dialog", "Nombre"))
        self.label_9.setText(_translate("Dialog", "Cobros Cuentas Corrientes"))
        self.label_12.setText(_translate("Dialog", "Gastos"))
        self.label.setText(_translate("Dialog", "Cuentas Corrientes"))
        self.label_10.setText(_translate("Dialog", "Nombre"))
        self.btnFinalizar.setText(_translate("Dialog", "Finalizar"))
        self.label_11.setText(_translate("Dialog", "Monto"))
        self.label_6.setText(_translate("Dialog", "Retiros de empleados"))
        self.label_3.setText(_translate("Dialog", "Monto"))
        self.label_16.setText(_translate("Dialog", "Total"))
        self.label_15.setText(_translate("Dialog", "Efectivo"))
        self.label_13.setText(_translate("Dialog", "Debitos"))
        self.label_14.setText(_translate("Dialog", "Cajero"))
        self.label_8.setText(_translate("Dialog", "Monto"))
        self.label_4.setText(_translate("Dialog", "Nombre"))
        self.label_7.setText(_translate("Dialog", "Nombre"))
        self.label_5.setText(_translate("Dialog", "Monto"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Planilla Diaria"))
        self.label_23.setText(_translate("Dialog", "Categoria"))
        self.label_24.setText(_translate("Dialog", "Nombre"))
        self.label_25.setText(_translate("Dialog", "Categoria"))
        self.label_26.setText(_translate("Dialog", "Nombre"))
        self.label_27.setText(_translate("Dialog", "Nombre"))
        self.label_28.setText(_translate("Dialog", "Categoria"))
        self.label_29.setText(_translate("Dialog", "Nombre"))
        self.label_30.setText(_translate("Dialog", "Categoria"))
        self.btnCargar.setText(_translate("Dialog", "Cargar Datos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Cargar Datos"))
        self.label_31.setText(_translate("Dialog", "Empleado"))
        self.label_32.setText(_translate("Dialog", "Francos"))
        self.label_33.setText(_translate("Dialog", "Carpeta "))
        self.chkCarpeta7.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.chkCarpeta4.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.chkCarpeta6.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.chkCarpeta5.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.chkCarpeta3.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.chkCarpeta2.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.chkCarpeta1.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.chkCarpeta8.setText(_translate("Dialog", "Con Carpeta hasta"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "Francos y carpetas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

